spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mmall_learning?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: azt153Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

profiles:
  active: dev

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  project: src/main/java
  resources: src/main/resources

mmall:
  password:
    salt: zyssdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,
  ftp:
    username: ACER
    password: azt153Win10
    server-ip: 192.168.137.1
    domain: ftp://192.168.137.1/
#    serverip: 111.231.1.237
#    user: ftpuser
#    password: azt153Ftpuser
#    domain: ftp://111.231.1.237/
server:
  port: 8082
